# Generated by Django 4.2.2 on 2023-06-25 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountprofile_alter_permissions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='telephone',
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='job_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multipleimages',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multipleimages',
            name='image_name',
            field=models.FileField(unique=True, upload_to='account_images'),
        ),
    ]
