# Generated by Django 4.2.2 on 2023-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_accountprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='receive_newsletters',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AccountProfile',
        ),
    ]
