# Generated by Django 4.2.2 on 2023-06-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_receive_newsletters_delete_accountprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
