# Generated by Django 4.2.2 on 2023-06-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_tax_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
