# Generated by Django 4.2.2 on 2023-06-26 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_billingadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='billing_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
