# Generated by Django 4.2.2 on 2023-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_billingadress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingadress',
            name='postcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billingadress',
            name='telephone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
