# Generated by Django 4.2.2 on 2023-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_billingadress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingadress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
