# Generated by Django 4.2.2 on 2023-06-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_billingadress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
