# Generated by Django 4.2.2 on 2023-06-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_billingadress_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
