# Generated by Django 4.2.2 on 2023-06-26 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_billingadress_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
