# Generated by Django 4.2.2 on 2023-07-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0003_alter_variations_variation_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variations',
            unique_together={('variation_category', 'variation_value')},
        ),
    ]
