# Generated by Django 4.2.2 on 2023-07-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0003_variationscategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('material', 'Material'), ('contition', 'Contition'), ('product_origin', 'Product Origin')], max_length=20),
        ),
        migrations.DeleteModel(
            name='VariationsCategory',
        ),
    ]
