# Generated by Django 4.2.2 on 2023-07-07 22:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productattrs_total_star_ratio_and_more'),
        ('variations', '0004_alter_variations_variation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variations',
            name='product',
        ),
        migrations.CreateModel(
            name='VariationsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('variation_category', models.CharField(choices=[('color', 'Color'), ('size', 'Size'), ('material', 'Material'), ('contition', 'Contition'), ('product_origin', 'Product Origin')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AlterField(
            model_name='variations',
            name='variation_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variations.variationscategory'),
        ),
    ]
