# Generated by Django 4.2.2 on 2023-07-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='variations',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='variations',
            field=models.ManyToManyField(to='variations.variations'),
        ),
    ]
