# Generated by Django 4.2.2 on 2023-07-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_cartitems_cart_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_items',
        ),
    ]
