# Generated by Django 4.2.2 on 2023-07-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cartitems_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart_items',
            new_name='cart',
        ),
    ]
