# Generated by Django 4.2.2 on 2023-07-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_rename_cart_items_cartitems_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='billing_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_address',
            field=models.BooleanField(default=False),
        ),
    ]
