# Generated by Django 4.2.2 on 2023-07-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cart_billing_address_cart_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='billing_address',
        ),
    ]
