# Generated by Django 4.2.2 on 2023-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_remove_cart_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variation',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
