# Generated by Django 4.2.2 on 2023-07-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_cartitems_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_address',
        ),
    ]
