# Generated by Django 4.2.2 on 2023-07-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_cart_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
