# Generated by Django 4.2.2 on 2023-06-29 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_id', models.CharField(max_length=200)),
                ('secontary_product_ids', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('price_b2b', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
