# Generated by Django 4.2.2 on 2023-07-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleProductImages',
        ),
    ]
