# Generated by Django 4.2.2 on 2023-07-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_star_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
