# Generated by Django 4.2.2 on 2023-07-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_multipleproductimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
