# Generated by Django 4.2.2 on 2023-07-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productattrs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattrs',
            options={'ordering': ['price']},
        ),
        migrations.RemoveField(
            model_name='productattrs',
            name='discount',
        ),
    ]
