# Generated by Django 4.2.2 on 2023-07-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_alter_variations_variation_category'),
        ('products', '0003_product_total_star_ratio_product_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattrs',
            name='total_star_ratio',
        ),
        migrations.RemoveField(
            model_name='productattrs',
            name='total_votes',
        ),
        migrations.AddField(
            model_name='productattrs',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='variations.variations'),
        ),
    ]
