# Generated by Django 4.2.2 on 2023-07-04 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_offer_discount_product_offer_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleProductImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='total_star_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
