# Generated by Django 4.2.2 on 2023-07-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_multipleproductimages_product_total_star_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_discount',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
