# Generated by Django 4.2.2 on 2023-07-13 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_rename_variation_category_variationscategory_name'),
        ('products', '0005_alter_productattrs_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattrs',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='variations.variations'),
        ),
    ]
