# Generated by Django 4.2.2 on 2023-07-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_offer_discount_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_duration',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
