# Generated by Django 4.2.2 on 2023-07-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_offer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
