# Generated by Django 4.2.2 on 2023-07-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_offer_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='secontary_product_ids',
            new_name='alternative_product_ids',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
