# Generated by Django 4.2.2 on 2023-07-16 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0004_alter_variations_unique_together'),
        ('products', '0007_rename_condition_productattrs_contition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattrs',
            name='contition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contition', to='variations.variations'),
        ),
    ]
