# Generated by Django 4.2.2 on 2023-07-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productattrs_contition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['total_star_ratio', 'created_at']},
        ),
    ]
